version: "2"

services:
  samba:
    image: dperson/samba:rpi
    restart: always
    command: '-u "anthony;pernia" -s "media;/media;yes;no;no;anthony;anthony"'
    stdin_open: true
    tty: true
    environment:
      - PERMISSIONS=0777
    ports:
      - 139:130
      - 445:445
    volumes:
      - ${LOCALTIME}:/etc/localtime
      - ${MOVIES}:/media/movies
      - ${SERIES}:/media/series
      - ${DOWNLOADS}:/media/downloads
      - ${DOCUMENTS}:/media/documents
      - ${TVSHOWS}:/media/tvshows
      - ${OTHERS}:/media/others