version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - WEBUI_PORT=8888
    volumes:
      - ${CONFIG}/qbittorrent-config:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 8888:8888
      - 6881:6881
      - 6881:6881/udp
    restart: always

#user admin
#pass adminadmin