version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /mnt/anthony-storage/config/radarr-config:/config
      - /mnt/anthony-storage/movies:/movies #optional
      - /mnt/anthony-storage/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped