version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
    volumes:
      - /mnt/anthony-storage/config/jackett-config:/config
      - /mnt/anthony-storage/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped