version: '3.3'
services:
    openbooks:
        ports:
            - '8089:80'
        volumes:
            - '/mnt/anthony-storage/documents:/books'
        restart: unless-stopped
        container_name: OpenBooks
        command: --persist
        environment:
          - BASE_PATH=/openbooks/
        image: evanbuss/openbooks:latest
