version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - JELLYFIN_PublishedServerUrl=192.168.1.7 #optional
    volumes:
      - ${CONFIG}/jellyfin_config/config:/config
      - ${CONFIG}/jellyfin_config/cache:/cache
      - /mnt/anthony-storage/tvshows:/data/tvshows
      - /mnt/anthony-storage/movies:/data/movies
      - /mnt/anthony-storage/media:/data/media
      - /mnt/anthony-storage/series:/data/series
      
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped